name: process_run
version: 1.1.0
description: Process run helpers for Linux/Win/Mac and which like feature for finding executables.
homepage: https://github.com/tekartik/process_run.dart/blob/master/packages/process_run

environment:
  sdk: ^3.4.0

dependencies:
  path: '>=1.8.0 <3.0.0'
  collection: '>=1.15.0 <3.0.0'
  string_scanner: '>=1.1.0 <3.0.0'
  yaml: '>=3.0.0 <5.0.0'
  meta: '>=1.3.0 <3.0.0'
  args: '>=2.0.0 <4.0.0'
  pub_semver: '>=2.0.0 <4.0.0'
  synchronized: '>=3.0.0 <5.0.0'

dev_dependencies:
  lints: '>=1.0.1'
  test: '>=1.16.2'
  async: '>=2.5.0'
  build_runner: '>=1.11.2'
  build_test: '>=1.3.7'
  build_version: '>=2.0.0'
executables:
  # Shell helper
  ds: shell

