name: Run CI Downgrade analyze
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }} / dart ${{ matrix.dart }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            dart: stable
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.4
        with:
          sdk: ${{ matrix.dart }}
      - run: dart --version
      - run: dart pub global activate dev_build
      - run: dart pub global run dev_build:run_ci --pub-downgrade --analyze --no-override --recursive
